### ISSUE TITLE
LICENSE.md

### ISSUE THREAD

**Issue by mheiber** [awalterschulze/regex-reexamined-coq#20]
Would someone be up for adding a LICENSE.md? I need to ask my employer for permission to contribute, and I think the request will be easier to approve if there is a license.

Apologies for the faff.

**Comment by awalterschulze** [comment]
Yes as long as it is a permissive licence, I am happy

Would that be possible?

Apache, MIT, BSD

Or what did you have in mind?

**Comment by mheiber** [comment]
Thanks, Walter. I'm not a lawyer, but any of the above sound fine.

Here's a link to the apache license for convenience: https://www.apache.org/licenses/LICENSE-2.0.txt

**Comment by awalterschulze** [comment]
I have made 3 pull requests, since I was too lazy to do it in my editor, I used the only the online gui.

https://github.com/awalterschulze/regex-reexamined-coq/pull/21
https://github.com/awalterschulze/regex-reexamined-coq/pull/22
https://github.com/awalterschulze/regex-reexamined-coq/pull/23
