### ISSUE TITLE
Some todos have already been done?

### ISSUE THREAD

**Issue by Nielius** [awalterschulze/regex-reexamined-coq#31]
I was reading some of the code and noticed that some of the code is listed as TODO (e.g.
https://github.com/awalterschulze/regex-reexamined-coq/blob/c1fb575a15a47128344f434e4f84a4ea467924c4/compare_regex.v#L87), but actually already has a solution (for the example, https://github.com/awalterschulze/regex-reexamined-coq/blob/master/compare_regex.v#L183)!

Is that because you weren't happy with the proof yet? Or shall I clean up this file and start removing the TODOs?

EDIT: better links:
https://github.com/awalterschulze/regex-reexamined-coq/blob/c1fb575a15a47128344f434e4f84a4ea467924c4/compare_regex.v#L80-L88
is solved by
https://github.com/awalterschulze/regex-reexamined-coq/blob/c1fb575a15a47128344f434e4f84a4ea467924c4/compare_regex.v#L183-L255

**Comment by awalterschulze** [comment]
Oh oops, that one slipped my mind.
Great catch :)
If there are more of those, then yes, please clean up.
