### ISSUE TITLE
Use `coq_makefile` at some point

### ISSUE THREAD

**Issue by Nielius** [awalterschulze/regex-reexamined-coq#35]
We can improve our Makefile by using `coq_makefile`. (Our current Makefile just recompiles everything every time.)

See <https://coq.inria.fr/refman/practical-tools/utilities.html#building-a-coq-project> for details.

**Comment by awalterschulze** [comment]
Sounds like a plan.
I am impressed that it is shipped with Coq and now I am even more enthusiastic.

github actions currently call the Makefile, so just a small note, after this change this would need to generate and call the `coq_makefile`
