### ISSUE TITLE
Make the inductive `is_sorted` the default

### ISSUE THREAD

**Issue by Nielius** [awalterschulze/regex-reexamined-coq#36]
We currently have three different definitions of `is_sorted`. Two of those are essentially the same (`is_sorted'` and `is_sorted''`), but there is an important difference between those two and the third (`is_sorted`). See https://github.com/awalterschulze/regex-reexamined-coq/blob/36de430013b663b142db04360512751e7be5bf26/sort.v#L10-L39

Our main definition (the one called `is_sorted`, without any apostrophes), is a match-statement, where at the end of all the matches, you get either `True` or `False`. I think it is probably better to take one of the inductive definition as our standard definition, for the following reason: with the current definition of `is_sorted`, if you have a `xs: List X` and you also have  a hypothesis `H : is_sorted xs`, that does not actually mean that `xs` is sorted, because `is_sorted xs` could just as well be false. So I think it's more natural to take the inductive definition, and I also think it's probably easier to prove things with that definition.

For example, I find it quite difficult (or at least more difficult than it should be) to prove the following lemma

```
Lemma is_sorted_sufficient_cond {X: Set} {tc: comparable X} (x x' : X) (xs: list X):
  ((compare x x' = Lt) \/ (compare x x' = Eq))
  -> is_sorted (x'::xs)
  -> is_sorted (x::x'::xs).
```

What do you guys think?

**Comment by awalterschulze** [comment]
Very happy to switch between which function has the tick and which doesn't.
And also happy to switch between which version we prove things about.
Please do what unblocks you and explain why in the pull request.

If others disagree and think it is easier to prove the old way, then that is a challenge for them to prove and us to learn from.  Either way we both win :)

**Comment by paulcadman** [comment]
We could prove that all the definitions are the same and then we can use
them interchangeably.

**Comment by awalterschulze** [comment]
I think this has been answered and can be closed?  Please reopen if I missed something.
